allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  core-js-pure: true
  less: true
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: true
